---
new_page_extension: html
auto_deploy: true
admin_path: "/cp1"
webhook_url: 
collections:
- path: ''
  label: Pages
  create: all
- path: _projects
  label: Projects
  create: all
  default_front_matter_template: project
- path: _people
  label: People
  create: all
  default_front_matter_template: person
- path: _posts
  label: Posts
  create: all
  default_front_matter_template: post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/cmsdemo"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
